### ISSUE TITLE
is It possible to extend this app to decode txs from bsc or polygon ?

### ISSUE THREAD

**Issue by jrcarlos2000** [EthTx/ethtx_ce#104]

**Comment by kchojn** [comment]
Hey @jrcarlos2000,
Yes, it is, you must have access to the node, preferably full-archive. After that, you need to add new chains to the list of chains in the index page. After brief testing, the polygon worked, I'm not sure about bsc. However, we have plans to extend, so there will be more chains supported by us in the future.
