### ISSUE TITLE
Hello,

### ISSUE THREAD

**Issue by WXF-WangXuFeng** [EthTx/ethtx_ce#114]
I'm running this code on my lunix server, trying to add support for bsc and polygon, but it reports an error: ModuleNotFoundError: No module named 'ethtx'. Can you tell me what to do? Do I have to install a copy of ethtx  by pip install ethts?

**Comment by kchojn** [comment]
Hello, 

Could you share how you installed the entire environment?

Regards

**Comment by kchojn** [comment]
I'm closing, if you need help. Let us know!

**Comment by htkcodes** [comment]
ailed building wheel for bitarray
    ERROR: Command errored out with exit status 1:
     command: /root/.local/share/virtualenvs/ethtx_ce-V1xLkuXk/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ej5_r6o4/bitarray/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ej5_r6o4/bitarray/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-v7vvy5p6/install-record.txt --single-version-externally-managed --compile --install-headers /root/.local/share/virtualenvs/ethtx_ce-V1xLkuXk/include/site/python3.9/bitarray
         cwd: /tmp/pip-install-ej5_r6o4/bitarray/
    Complete output (18 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.9
    creating build/lib.linux-x86_64-3.9/bitarray
    copying bitarray/util.py -> build/lib.linux-x86_64-3.9/bitarray
    copying bitarray/__init__.py -> build/lib.linux-x86_64-3.9/bitarray
    copying bitarray/test_bitarray.py -> build/lib.linux-x86_64-3.9/bitarray
    copying bitarray/test_util.py -> build/lib.linux-x86_64-3.9/bitarray
    warning: build_py: byte-compiling is disabled, skipping.
    
    running build_ext
    building 'bitarray._bitarray' extension
    creating build/temp.linux-x86_64-3.9
    creating build/temp.linux-x86_64-3.9/bitarray
    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/root/.local/share/virtualenvs/ethtx_ce-V1xLkuXk/include -I/usr/include/python3.9 -c bitarray/_bitarray.c -o build/temp.linux-x86_64-3.9/bitarray/_bitarray.o
    error: command 'x86_64-linux-gnu-gcc' failed: No such file or directory
    ----------------------------------------
ERROR: Command errored out with exit status 1: /root/.local/share/virtualenvs/ethtx_ce-V1xLkuXk/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ej5_r6o4/bitarray/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ej5_r6o4/bitarray/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-v7vvy5p6/install-record.txt --single-version-externally-managed --compile --install-headers /root/.local/share/virtualenvs/ethtx_ce-V1xLkuXk/include/site/python3.9/bitarray Check the logs for full command output.

**Comment by kchojn** [comment]
Hey @htkcodes,
please install:
```sh
sudo apt-get install libxml2-dev libxslt1-dev gcc
```
```sh
sudo apt-get install python3-dev 
OR
sudo apt-get install python3.x-dev (for specific python version)
```

and let me know, if it helps, we will extend the `README` with this information.

**Comment by htkcodes** [comment]
Thanks worked..
