### ISSUE TITLE
Dependencies error

### ISSUE THREAD

**Issue by enmohsinali** [EthTx/ethtx_ce#71]
Getting some dependencies error.

![image](https://user-images.githubusercontent.com/37579751/147316272-36ad8668-8313-42de-94b6-064da2b881b2.png)

I proceed with --skip-lock but then getting dependencies error while building docker image

![image](https://user-images.githubusercontent.com/37579751/147316737-ee303870-2f46-4248-800d-40cfa12120a4.png)

**Comment by piotr-rudnik** [comment]
Hey, thanks for reporting this. So, I was able to reproduce this with docker. Looks like there are problem with sub-dependencies from ethereum, package which is deprecated and should not be used. Will try to solve this today.

**Comment by kchojn** [comment]
Hello, all problems should be solved. If you still have a problem, please write and we will help!

**Comment by enmohsinali** [comment]
Yes the problem has been solved.

Thank you so much.
